import { expect, test } from '@playwright/test'
import { captureBrowserErrors, expectNoHorizontalOverflow, loginDemo } from './fixtures'

test('@platform Platform Console navigation excludes enterprise and relay operations', async ({ page }) => {
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/overview')
  await expect(page).toHaveURL(/\/platform\/overview$/)
  if ((page.viewportSize()?.width || 0) <= 640) {
    await page.getByRole('button', { name: 'Open navigation' }).click()
  }
  await expect(page.getByRole('heading', { level: 1, name: 'Platform overview' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Provider Connections' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Tenants & principals' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Delegated access' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Usage delivery' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'API Keys' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Users / RBAC' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Departments' })).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Customers' })).toHaveCount(0)
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})

test('@platform Platform Console creates delegated access with a one-time secret', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-desktop', 'The delegated access lifecycle runs once against the isolated demo runtime.')
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/integrations')
  await expect(page).toHaveURL(/\/platform\/integrations$/)
  await page.getByRole('button', { name: 'New delegated access' }).click()
  const integrationName = `browser-integration-${Date.now()}`
  await page.getByLabel('Integration name').fill(integrationName)
  await page.getByLabel('Key ID').fill(`browser_${Date.now()}`)
  await page.getByLabel('Gateway audience').fill('https://gateway.example/v1')
  await page.getByLabel('Model allowlist', { exact: true }).fill('gpt-4o-mini')
  await page.getByRole('spinbutton', { name: 'QPS limit', exact: true }).fill('2')
  await page.getByLabel('Monthly token limit', { exact: true }).fill('1000')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Copy now. This integration secret is shown only once.')).toBeVisible()
  const secretInput = page.locator('.notice.success input').last()
  await expect(secretInput).toHaveValue(/asc_/)
  const secret = await secretInput.inputValue()
  await page.reload()
  await expect(page.locator(`input[value="${secret}"]`)).toHaveCount(0)
  await expect(page.getByText(integrationName, { exact: true })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})

test('@platform Platform Console creates a signed usage delivery destination', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-desktop', 'The usage delivery lifecycle runs once against the isolated demo runtime.')
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/integrations')
  await page.getByRole('button', { name: 'New delegated access' }).click()
  await page.getByLabel('Integration name').fill(`browser-usage-integration-${Date.now()}`)
  await page.getByLabel('Key ID').fill(`usage_browser_${Date.now()}`)
  await page.getByLabel('Gateway audience').fill('https://gateway.example/v1')
  await page.getByLabel('Model allowlist', { exact: true }).fill('gpt-4o-mini')
  await page.getByRole('spinbutton', { name: 'QPS limit', exact: true }).fill('2')
  await page.getByLabel('Monthly token limit', { exact: true }).fill('1000')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Delegated access integration created.')).toBeVisible()

  await page.goto('/platform/usage-sinks')
  await expect(page).toHaveURL(/\/platform\/usage-sinks$/)
  await page.getByRole('button', { name: 'New usage delivery' }).click()
  const deliveryName = `browser-usage-${Date.now()}`
  await page.getByLabel('Delivery name').fill(deliveryName)
  await page.getByLabel('HTTPS endpoint').fill('https://billing.example/events')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Copy now. This signing secret is shown only once.')).toBeVisible()
  const secret = await page.locator('.notice.success input').last().inputValue()
  await expect(secret).toMatch(/^aus_/)
  await page.reload()
  await expect(page.locator(`input[value="${secret}"]`)).toHaveCount(0)
  await expect(page.getByText(deliveryName, { exact: true })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})

test('@platform Platform Console configures JWT/JWKS delegated access without a shared secret', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-desktop', 'The JWT integration lifecycle runs once against the isolated demo runtime.')
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/integrations')
  await page.getByRole('button', { name: 'New delegated access' }).click()
  await page.getByLabel('Authentication method').selectOption('jwt_jwks')
  await expect(page.getByLabel('JWT issuer')).toBeVisible()
  await expect(page.getByLabel('JWKS URL')).toBeVisible()
  await expect(page.getByLabel('Subject claim')).toHaveValue('sub')
  const runID = Date.now()
  const integrationName = `browser-jwt-${runID}`
  const issuer = `https://identity-${runID}.example`
  await page.getByLabel('Integration name').fill(integrationName)
  await page.getByLabel('Key ID').fill(`jwt_browser_${runID}`)
  await page.getByLabel('Gateway audience').fill('https://gateway.example/v1')
  await page.getByLabel('JWT issuer').fill(issuer)
  await page.getByLabel('JWKS URL').fill(`${issuer}/.well-known/jwks.json`)
  await page.getByLabel('Model allowlist', { exact: true }).fill('gpt-4o-mini')
  await page.getByRole('spinbutton', { name: 'QPS limit', exact: true }).fill('2')
  await page.getByLabel('Monthly token limit', { exact: true }).fill('1000')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Delegated access integration created.')).toBeVisible()
  await expect(page.getByText(integrationName, { exact: true })).toBeVisible()
  const row = page.locator('tr', { hasText: integrationName })
  await expect(row.getByText('jwt_jwks', { exact: false })).toBeVisible()
  await expect(row.getByRole('button', { name: 'Rotate secret' })).toHaveCount(0)
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})

test('@platform Platform JWT/JWKS configuration remains usable on compact and mobile viewports', async ({ page }) => {
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/integrations')
  await page.getByRole('button', { name: 'New delegated access' }).click()
  await page.getByLabel('Authentication method').selectOption('jwt_jwks')
  await expect(page.getByLabel('JWT issuer')).toBeVisible()
  await expect(page.getByLabel('JWKS URL')).toBeVisible()
  await expect(page.getByLabel('Subject claim')).toHaveValue('sub')
  await expect(page.getByLabel('Model allowlist claim')).toBeVisible()
  await expect(page.getByLabel('QPS limit claim')).toBeVisible()
  await expect(page.getByLabel('Monthly token limit claim')).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})

test('@platform Platform Console creates service API Keys', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-desktop', 'The API credential lifecycle runs once against the isolated demo runtime.')
  const errors = captureBrowserErrors(page)
  await loginDemo(page)

  await page.goto('/platform/api-keys')
  await expect(page).toHaveURL(/\/platform\/api-keys$/)

  await page.getByRole('button', { name: /New (workspace|service) key/ }).click()
  await expect(page.getByLabel('Tenant')).toHaveValue('ptn_default')
  await expect(page.getByLabel('Gateway principal')).toHaveValue('gpr_default_service')
  const keyName = `platform-service-${Date.now()}`
  await page.getByLabel('Name').fill(keyName)
  await page.getByLabel('Key type').selectOption('service')
  await page.getByLabel('Model allowlist').fill('gpt-4o-mini')
  await page.getByRole('button', { name: 'Save' }).click()
  await expect(page.getByText('Copy now. This key is shown only once.')).toBeVisible()
  await expect(page.locator('tr', { hasText: keyName }).getByRole('cell', { name: 'service', exact: true })).toBeVisible()
  await expectNoHorizontalOverflow(page)
  expect(errors).toEqual([])
})
